service: cobol-lambda
frameworkVersion: '2'

provider:
  name: aws
  # We provide our own runtime in the bootstrap file
  runtime: provided

package:
  include:
    - lib/**
    - hello
    - bootstrap

functions:
  hello:
    handler: ./hello
    events:
      - http: GET /
